/*====================================================
Topic : Joins
Author : Mohammed Fazil
Database : Oracle SQL
====================================================*/

--1.	Employee with department. 

SELECT E.EMP_ID , E.EMP_NAME , E.DEPT_ID ,E.SALARY , D.DEPT_NAME 
FROM EMPLOYEE E INNER JOIN DEPARTMENT D
ON E.DEPT_ID = D.DEPT_ID; --1

--2.	Customer with orders. 

SELECT C.CUSTOMER_ID , C.CUSTOMER_NAME , O.ORDER_ID , O.STATUS 
FROM CUSTOMER C INNER JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID; --2

--3.	Orders with products. 

SELECT O.ORDER_ID , O.PRODUCT_ID , P.PRODUCT_NAME ,P.CATEGORY
FROM ORDER_DETAILS O LEFT OUTER JOIN  PRODUCT P
ON O.PRODUCT_ID = P.PRODUCT_ID; --3

--4.	Employee with project. 

SELECT E.EMP_ID , E.EMP_NAME , E.DEPT_ID ,E.SALARY , EP.PROJECT_ID , EP.HOURS_WORKED 
FROM EMPLOYEE E INNER JOIN EMPLOYEE_PROJECT EP
ON E.EMP_ID = EP.EMP_ID; --4

--5.	Project with employees.

SELECT P.PROJECT_ID, P.PROJECT_NAME, E.EMP_ID, E.EMP_NAME
FROM PROJECT P
INNER JOIN EMPLOYEE_PROJECT EP
ON P.PROJECT_ID = EP.PROJECT_ID
INNER JOIN EMPLOYEE E
ON EP.EMP_ID = E.EMP_ID;--5

--6.	Employee with manager. 

SELECT E.EMP_ID , E.EMP_NAME , E.DEPT_ID ,E.SALARY,M.EMP_NAME MANAGER
FROM EMPLOYEE E INNER JOIN EMPLOYEE M
ON E.MANAGER_ID = M.EMP_ID; --6

--7.	Product with order details. 

SELECT P.PRODUCT_ID , P.PRODUCT_NAME , O.ORDER_ID 
FROM PRODUCT P  INNER JOIN ORDER_DETAILS O
ON P.PRODUCT_ID = O.PRODUCT_ID; --7

--8.	Customer with ordered products. 

SELECT DISTINCT  C.CUSTOMER_ID , C.CUSTOMER_NAME , O.ORDER_ID ,P.PRODUCT_ID, P.PRODUCT_NAME
FROM CUSTOMER C , ORDERS O , PRODUCT P , ORDER_DETAILS OD
WHERE C.CUSTOMER_ID = O.CUSTOMER_ID
AND P.PRODUCT_ID = OD.PRODUCT_ID
AND O.ORDER_ID = OD.ORDER_ID; --8

SELECT DISTINCT  C.CUSTOMER_ID , C.CUSTOMER_NAME , O.ORDER_ID ,P.PRODUCT_ID, P.PRODUCT_NAME
FROM CUSTOMER C
JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID
JOIN ORDER_DETAILS OD
ON O.ORDER_ID = OD.ORDER_ID
JOIN PRODUCT P
ON OD.PRODUCT_ID = P.PRODUCT_ID --8

--9.	Department with employees. 

SELECT E.EMP_ID , E.EMP_NAME , E.DEPT_ID ,E.SALARY , D.DEPT_NAME 
FROM EMPLOYEE E RIGHT OUTER JOIN DEPARTMENT D
ON E.DEPT_ID = D.DEPT_ID; --9

/*DEPARTMENT
LEFT JOIN EMPLOYEE*/

--10.	Employee, department, and project together.

SELECT E.EMP_ID , E.EMP_NAME , E.DEPT_ID ,E.SALARY , D.DEPT_NAME ,P.PROJECT_NAME
FROM EMPLOYEE E , DEPARTMENT D , PROJECT P , EMPLOYEE_PROJECT EP
WHERE E.DEPT_ID = D.DEPT_ID
AND P.PROJECT_ID = EP.PROJECT_ID
AND E.EMP_ID = EP.	EMP_ID; --10
