CREATE TABLE EMPLOYEE
(
    EMP_ID NUMBER PRIMARY KEY,
    EMP_NAME VARCHAR2(30),
    GENDER VARCHAR2(6),
    DOB DATE,
    HIRE_DATE DATE,
    SALARY NUMBER(10,2),
    COMMISSION NUMBER(10,2),
    DEPT_ID NUMBER,
    MANAGER_ID NUMBER,
    JOB_TITLE VARCHAR2(30),
    EMAIL VARCHAR2(30),
    PHONE VARCHAR2(15),
    STATUS VARCHAR2(10),

    CONSTRAINT DEPT_001
    FOREIGN KEY (DEPT_ID)
    REFERENCES DEPARTMENT(DEPT_ID),

    CONSTRAINT MAG_001
    FOREIGN KEY (MANAGER_ID)
    REFERENCES EMPLOYEE(EMP_ID)
);

SELECT * FROM EMPLOYEE;